import React, { FC } from 'react';
import { Body, Container, Font, Head, Html, Section, Tailwind } from '@react-email/components';
import {
    AutoGeneratedNote,
    BidSection,
    ContactsSection,
    EdoEmployeeSection,
    GreetingSection,
} from './DocumentEmailSections';
import { DocumentEmailTemplateProps } from './document-email-template.types';
export type {
    DocumentEmailTemplateProps,
    EdoEmployeeProps,
} from './document-email-template.types';

export const DocumentEmailTemplate: FC<DocumentEmailTemplateProps> = ({
    name,
    phone,
    edoEmployee,
    bidHtml,
}) => (
    <Tailwind>
        <Html lang="ru">
            <Head>
                <Font
                    fontFamily="Roboto"
                    fallbackFontFamily="Arial"
                    webFont={{
                        url: 'https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap',
                        format: 'woff2',
                    }}
                />
            </Head>
            <Body className="m-0 bg-[#f8f9fa] px-2 py-3">
                <Container className="mx-auto max-w-[980px] rounded-xl bg-white p-6 shadow-[0_1px_2px_rgba(60,64,67,0.08),0_2px_8px_rgba(60,64,67,0.06)]">
                    <Section>
                        <AutoGeneratedNote />
                        <GreetingSection name={name} phone={phone} />
                        <ContactsSection />
                        {/* <BidSection bidHtml={bidHtml} /> */}
                        {edoEmployee ? (
                            <EdoEmployeeSection {...edoEmployee} />
                        ) : null}
                    </Section>
                </Container>
            </Body>
        </Html>
    </Tailwind>
);
