import React, { FC } from 'react';
import { Hr, Img, Link, Section, Text } from '@react-email/components';
import { HR, LINK, NAME_ACCENT, P, TITLE_CENTER } from './document-email-template.constants';
import { EdoEmployeeProps } from './document-email-template.types';

interface GreetingSectionProps {
    name: string;
    phone: string;
}

export const AutoGeneratedNote: FC = () => (
    <Text className="m-0 mb-4 text-[13px] leading-[1.55] text-[#5f6368]">
        <i>
            Письмо сформировано автоматически. При ответе, просто
            нажмите&nbsp;<b>«ОТВЕТИТЬ»</b>&nbsp;или введите{' '}
            <Link href="mailto:ppk@alfasibir.ru" title="mailto:ppk@alfasibir.ru" className={LINK}>
                <b>
                    <i>ppk@alfasibir.ru</i>
                </b>
            </Link>{' '}
            в строке «Адрес получателя/Кому».
        </i>
    </Text>
);

export const GreetingSection: FC<GreetingSectionProps> = ({ name, phone }) => {
    const hasName = Boolean(name);
    const hasPhone = Boolean(phone);

    return (
        <>
            <Text className={P}>
                Добрый день
                {hasName ? (
                    <>
                        , <span className={NAME_ACCENT}>{name}</span>
                    </>
                ) : null}
                !<br />
                Во вложении -&nbsp;<b>Договор</b>,&nbsp;
                <b>Счет </b>и <b>Акт </b>на согласование.
            </Text>

            <Text className={P}>
                Пожалуйста, проверьте <b>реквизиты</b>, а также
                <b> текст документов</b>.
            </Text>

            <ul className="m-0 mb-5 list-disc pl-[22px] text-[15px] leading-[1.55] text-[#202124]">
                <li className="mb-3">
                    <b>
                        Если документы соответствуют требованиям Вашего
                        учреждения
                    </b>{' '}
                    - подпишите, пожалуйста, его в системе ЭДО. Если Ваше
                    учреждение не использует систему ЭДО, то направьте нам
                    ответным e-mail скан Договора, заверенного с Вашей стороны
                    печатью и подписью руководителя.
                    <br />
                    Наш
                    <b>
                        &nbsp;СБИС&nbsp;ID: 2BEbe3508291e7a494ca4d051e2230821b1{' '}
                    </b>
                    (Оператор&nbsp;ООО &quot;Компания &quot;Тензор&quot;)
                </li>
                <li className="mb-0">
                    <b>Если документы требуют корректировки</b> -
                    откорректированный текст договора, вышлите, пожалуйста,
                    ответным e-mail в текстовом формате (например Word).
                </li>
            </ul>

            <Text className={P}>
                В течение 1 рабочего дня с момента направления данного письма
                на номер телефона
                {hasPhone ? (
                    <>
                        , <span className={NAME_ACCENT}>{phone}</span>
                    </>
                ) : null}{' '}
                Вам позвонит робот Ирина для подтверждения получения документов.
                Просим Вас подтвердить получение простым ответом &quot;ДА&quot;.
            </Text>
        </>
    );
};

export const ContactsSection: FC = () => (
    <Text className={P}>
        С уважением,
        <br />
        Чехуркина Наталья,
        <br />
        Специалист по документообороту,
        <br />
        Центр правовой поддержки ООО &quot;АЛЬФАЦЕНТР&quot;,
        <br />
        Почтовый адрес: 630073, г. Новосибирск, а/я 202
        <br />
        тел. многоканальный: 8 (383) 383-24-15 доб.106
        <br />
        <Link href="http://e.mail.ru/compose/?mailto=mailto%3appk@alfasibir.ru" className={LINK}>
            ppk@alfasibir.ru
        </Link>
        <br />
        Сайт компании:{' '}
        <Link href="https://alfacentr.org/" className={LINK}>
            https://alfacentr.org
        </Link>
        <br />
        <span className="text-[#5f6368]">Социальные сети:</span>
        <br />
        <Link href="https://vk.com/alfacentr_nsk" className={LINK}>
            https://vk.com/alfacentr_nsk
        </Link>
        <br />
        <Link href="https://ok.ru/group/68876292653111" className={LINK}>
            https://ok.ru/group/68876292653111
        </Link>
        <br />
        <Img
            width={386}
            height={47}
            alt="logo"
            src="https://i.imgur.com/DucbqTv.png"
            className="mt-3 block h-auto max-w-full border-0"
        />
    </Text>
);

export const BidSection: FC<{ bidHtml?: string }> = ({ bidHtml }) => (
    <>
        <Hr className={HR} />
        <Text className={TITLE_CENTER}>
            <b>Исходная заявка клиента:</b>
        </Text>
        <div
            className={P}
            dangerouslySetInnerHTML={{ __html: `${bidHtml ?? ''}<br>` }}
        />
    </>
);

export const EdoEmployeeSection: FC<EdoEmployeeProps> = ({
    dealUrl,
    edoComment,
    userName,
    dealId,
    companyName,
}) => {
    return (
        <Section>
            <Hr className={HR} />
            <Text className={TITLE_CENTER}>
                <b>Комментарий для сотрудника ОДО:</b>
            </Text>
            <Text className={`${P} mb-5`}>{edoComment || ''}</Text>
            <Hr className={HR} />
            <Text className={TITLE_CENTER}>
                <b>Исполнитель:</b>
            </Text>
            <Text className={P}>{userName || ''}</Text>
            <Text className={`${P} mb-0`}>
                <Link href={dealUrl} className={LINK}>
                    Документация
                </Link>
                <br />
                {dealId} {companyName ? `"${companyName}"` : ''}
            </Text>
        </Section>
    );
};
