version: '3.8'

services:
  

  front-alfacentr:
    build:
      context: .
      dockerfile: docker/Dockerfile.front
      args:
        APP: front 
    container_name: front-alfacentr-dev
    ports:
      - "${PORT_ALFA}:3000"         # API доступен снаружи
    environment:
      - IN_BITRIX=true
      - LOG_FILE_PATH=/app/logs/server.log
 
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - app-network-alfacentr


  api-alfacentr:
    build:
      context: .
      dockerfile: docker/Dockerfile.back
      args:
        APP: back 

    container_name: nest-api-alfacentr
    ports:
      - "${PORT_API_ALFA}:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis-alfacentr
      - REDIS_PORT=6379
      - PORT=3000   
      - DATABASE_URL=mysql://root:cfdx@db-alfacentr:3306/bitrix  
      - LOG_FILE_PATH=/app/logs/server.log         
               # для app.listen
    depends_on:
      - db-alfacentr
      - redis-alfacentr


    restart: unless-stopped

    volumes:
      - ./keys:/app/keys
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks:
      - app-network-alfacentr

  redis-alfacentr:
    image: redis:7
    container_name: redis-alfacentr
    ports:
      - "6379:6379"
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "redis-cli", "ping"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 60
    networks:
      - app-network-alfacentr

  db-alfacentr:
    image: mysql:8.0
    container_name: db-alfacentr
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: cfdx # Задай свой пароль для root
      MYSQL_DATABASE: bitrix # Название базы данных
      # MYSQL_USER: root # Имя пользователя
      MYSQL_PASSWORD: cfdx # Пароль пользователя
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./apps/back/db_dev:/docker-entrypoint-initdb.d
    networks:
      - app-network-alfacentr

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pcfdx"]
      interval: 5s
      timeout: 3s
      retries: 5


volumes:
  db_data: 

networks:
  app-network-alfacentr:
    driver: bridge
    name: app-network-alfacentr

