import { RQ_TYPE } from "@workspace/bx-rq"
import { DocumentRqAgent } from "../model/slice/DocumentRqSlice"
import { EnumOrganizationRqFields } from "../type/document-rq.type"

export const PROVIDER_RQ_CONST = {
    shortName: 'ООО Альфацентр',
    fullname: 'Общество с ограниченной ответственностью "Альфацентр"',
    inn: '5404519376',
    kpp: '540401001',
    address: '630054, г.  Новосибирск, Ул. Крашенинникова, д. 2, кв. 22',
    primaryAddress: '630073, Россия,  г. Новосибирск, а/я 202 ',
    phone: '8(383)209-32-15',
    email: 'providerRq.email',
    bank: 'ООО "Банк Точка" ',
    bankAddress: 'г. Москва',
    bik: '044525104',
    rs: '40702810704500008836',
    ks: '30101810745374525104',
    ogrn: '1145476103915',
    edo: 'ООО "Компания "Тензор"',
    sbisId: '2BEbe3508291e7a494ca4d051e2230821b1',
    based: 'устава',
    directorCase: 'Циммера Александра Валентиновича',
    directorName: 'Циммера Александр Валентинович',
    directorFio: 'Циммера А. В.',
    directorPosition: 'Директор',
    directorPositionCase: 'Директора',
    accountant: 'Управляющий',
}

export const Provider: DocumentRqAgent<RQ_TYPE.ORGANIZATION> = {

    [EnumOrganizationRqFields.NAME]: PROVIDER_RQ_CONST.shortName,
    [EnumOrganizationRqFields.FULLNAME]: PROVIDER_RQ_CONST.fullname,
    [EnumOrganizationRqFields.INN]: `ИНН: ${PROVIDER_RQ_CONST.inn}`,
    [EnumOrganizationRqFields.ADDRESS]: `Юридический адрес: ${PROVIDER_RQ_CONST.address}`,
    [EnumOrganizationRqFields.PRIMARY_ADDRESS]: `Почтовый адрес: ${PROVIDER_RQ_CONST.primaryAddress}`,
    [EnumOrganizationRqFields.PHONE]: `Телефон: ${PROVIDER_RQ_CONST.phone}`,
    [EnumOrganizationRqFields.EMAIL]: `Эл. почта: ${PROVIDER_RQ_CONST.email}`,
    [EnumOrganizationRqFields.BANK]: `в Банке: ${PROVIDER_RQ_CONST.bank} ${PROVIDER_RQ_CONST.bankAddress}`,
    [EnumOrganizationRqFields.BANK_ADDRESS]: ` ${PROVIDER_RQ_CONST.bankAddress}`,
    [EnumOrganizationRqFields.BIK]: `БИК: ${PROVIDER_RQ_CONST.bik}`,
    [EnumOrganizationRqFields.RS]: `р/с: ${PROVIDER_RQ_CONST.rs}`,
    [EnumOrganizationRqFields.KS]: `к/с: ${PROVIDER_RQ_CONST.ks}`,
    [EnumOrganizationRqFields.OGRN]: `ОГРН: ${PROVIDER_RQ_CONST.ogrn}`,
    [EnumOrganizationRqFields.EDO]: `Оператор ЭДО: ${PROVIDER_RQ_CONST.edo}`,
    [EnumOrganizationRqFields.SBIS_ID]: `СБИС ID: ${PROVIDER_RQ_CONST.sbisId}`,   
    [EnumOrganizationRqFields.BASED]: PROVIDER_RQ_CONST.based,
    [EnumOrganizationRqFields.KPP]: `КПП: ${PROVIDER_RQ_CONST.kpp}`,
    [EnumOrganizationRqFields.SHORTNAME]: `Сокращенное наименование: ${PROVIDER_RQ_CONST.shortName}`,
    [EnumOrganizationRqFields.DIRECTOR_POSITION]: PROVIDER_RQ_CONST.directorPosition,
    [EnumOrganizationRqFields.DIRECTOR_POSITION_CASE]: PROVIDER_RQ_CONST.directorPositionCase,
    [EnumOrganizationRqFields.DIRECTOR_FIO]: PROVIDER_RQ_CONST.directorFio,
    [EnumOrganizationRqFields.DIRECTOR_NAME]: PROVIDER_RQ_CONST.directorName,
    [EnumOrganizationRqFields.DIRECTOR_CASE]: PROVIDER_RQ_CONST.directorCase,
    [EnumOrganizationRqFields.ACCOUNTANT]: PROVIDER_RQ_CONST.accountant,
    [EnumOrganizationRqFields.OTHER]: '',
    [EnumOrganizationRqFields.TYPE]: RQ_TYPE.ORGANIZATION,
}

