export enum EBXEntity {
    DEAL = 'deal',
    COMPANY = 'company',
    CONTACT = 'contact',
    LEAD = 'lead',
    TASK = 'task',
    ITEM = 'item',
    TYPE = 'type',
    TIMELINE_COMMENT = 'timeline.comment',
    TIMELINE_ITEM = 'timeline.item',
    PRODUCT_ROW = 'productrow',
    USER_FIELD = 'userfield',
    USER_FIELD_CONFIG = 'userfieldconfig',
    USER_FIELD_ENUMERATION = 'userfield.enumeration',
    LISTS = 'lists',
    ACTIVITY = 'activity',
    FILE = 'file',
    FOLDER = 'folder',
    STORAGE = 'storage',
    CATEGORY = 'category',
    STATUS = 'status',
    PRODUCT = 'product',
    RPA = 'rpa',
    USER = 'user',
}
