export enum EBxNamespace {
    CRM = 'crm',
    TASKS = 'tasks',
    LISTS = 'lists',
    CRM_ITEM = 'crm.item',
    WITHOUT_NAMESPACE = 'without.namespace',
    DISK = 'disk',
    CATALOG = 'catalog',
    RPA = 'rpa',
}

export enum EBxMethod {
    ADD = 'add',
    SET = 'set',
    UPDATE = 'update',
    GET = 'get',
    USER_FIELD_LIST = 'userfield.list',
    USER_FIELD_GET = 'userfield.get',
    USER_FIELD_ADD = 'userfield.add',
    LIST = 'list',
    DELETE = 'delete',
    CONTACT_ITEMS_SET = 'contact.items.set',
    CONTACT_ADD = 'contact.add',
    CONTACT_ITEMS_GET = 'contact.items.get',
    FIELD_GET = 'field.get',
    FIELDS = 'fields',
    GET_LIST = 'getlist',
    GET_TYPES = 'gettypes',
    GET_CHILDREN = 'getchildren',
    GET_BY_ENTITY_TYPE_ID = 'getByEntityTypeId',
    SEARCH = 'search',
    CURRENT = 'current',
    USER_FIELD_UPDATE = 'userfield.update',
    USER_FIELD_DELETE = 'userfield.delete',
    MOVE_TO = 'moveto',
    RESTORE = 'restore',
    GET_FIELDS = 'getfields',
    GET_VERSIONS = 'getVersions',
    MARK_DELETED = 'markdeleted',
    COPY_TO = 'copyto',
    GET_EXTERNAL_LINK = 'getExternalLink',
    GET_EXTERNAL_LINK_LOWER = 'getexternallink',
    RENAME = 'rename',
    UPLOAD_FILE = 'uploadfile',
    UPLOAD_VERSION = 'uploadversion',
    RESTORE_FROM_VERSION = 'restoreFromVersion',
    ADD_FOLDER = 'addfolder',
    ADD_SUBFOLDER = 'addsubfolder',
    SHARE_TO_USER = 'sharetouser',
    DELETE_TREE = 'deletetree',
    PIN = 'pin',
}
